src/main/java/kr/allcll/seatfinder/pin/PinApi.java
src/main/java/kr/allcll/seatfinder/seat/SeatApi.java
src/main/java/kr/allcll/seatfinder/subject/SubjectApi.java

- api 뼈대 코드를 작성해 보았어요. 
- 도메인명도 임의로 정했어요. 
간단한 작업으로 리뷰 후 바로 머지해도 괜찮을 것 같아요! 
- 다음 도메인명 괜찮은지 궁금합니다. 
- seat
- pin
- subject
- 패키지 구조를 도메인 단위로 잡았는데 괜찮은지 궁금합니다.

feat: api 뼈대 코드 작성

---

src/main/java/kr/allcll/seatfinder/pin/Pin.java
src/main/java/kr/allcll/seatfinder/pin/PinApi.java
src/main/java/kr/allcll/seatfinder/pin/PinService.java
src/test/java/kr/allcll/seatfinder/pin/PinServiceTest.java

핀을 제거하는 기능을 구현했습니다.
제가 예외 처리를 제대로 안 한 지점이 있다던가, 정책을 제대로 반영하지 않은 곳이 있는 지 검토해주세요~!
그리고 [feat: pin 등록 api 개발](https://github.com/allcll/seat-finder/pull/9) 얘보다 이 아이 먼저 머지해야해용

feat: pin 제거 기능 구현

---

src/main/java/kr/allcll/seatfinder/config/ScheduleConfig.java
src/main/java/kr/allcll/seatfinder/seat/Seat.java
src/main/java/kr/allcll/seatfinder/seat/SeatService.java
src/main/java/kr/allcll/seatfinder/seat/SeatStorage.java
src/main/java/kr/allcll/seatfinder/seat/dto/SeatResponse.java
src/main/java/kr/allcll/seatfinder/seat/dto/SeatsResponse.java
src/main/java/kr/allcll/seatfinder/sse/SseApi.java
src/main/java/kr/allcll/seatfinder/sse/SseEmitterStorage.java
src/main/java/kr/allcll/seatfinder/sse/SseErrorHandler.java
src/main/java/kr/allcll/seatfinder/sse/SseEventBuilderFactory.java
src/main/java/kr/allcll/seatfinder/sse/SseService.java
src/main/java/kr/allcll/seatfinder/subject/Subject.java
src/main/resources/application.yml
src/test/java/kr/allcll/seatfinder/seat/SeatServiceTest.java
src/test/java/kr/allcll/seatfinder/sse/SseErrorHandlerTest.java
src/test/java/kr/allcll/seatfinder/sse/SseEventBuilderFactoryTest.java
src/test/java/kr/allcll/seatfinder/sse/SseIntegrationTest.java
src/test/java/kr/allcll/seatfinder/sse/SseServiceTest.java
src/test/java/kr/allcll/seatfinder/subject/SubjectTest.java
src/test/java/kr/allcll/seatfinder/support/fixture/SubjectFixture.java
src/test/resources/application.yml

실시간으로 여석을 조회하는 기능을 구현했습니다. 데이터를 실시간으로 전달하기 위해 SSE를 사용했습니다. 
아직 테스트를 작성하지 않았는데, 추가할게요! sse 경험이 없으면 코드 리뷰에 좀 오랜 시간이 걸릴 것 같아서 구현한 내용부터 올려요. 이후에 구현부가 달라질 수 있다는 점을 고려해 주세요 😀

feat: 실시간 교양 여석 조회 기능 구현 

---

.github/workflows/deploy-to-dev.yml

개발 서버에 배포하는 스크립트를 작성했어요! 
스크립트 보시면 쉽게 이해할 수 있을 겁니다~

chore: 배포 스크립트 작성

---

src/main/java/kr/allcll/seatfinder/basket/Basket.java
src/main/java/kr/allcll/seatfinder/subject/Subject.java

테이블 명을 명시해주지 않아서 db 조회가 안되어 에러가 발생하는 이슈가 있었습니다.

hotfix: 엔티티 테이블명 어노테이션 추가

---

.github/workflows/deploy-to-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml
src/main/resources/logback-spring.xml

환경에 따라 설정 파일이 분리되어 있지 않은 문제가 있었습니다. 
기존에 application.yml만 존재했는데, 이 파일을 application-local.yml로 수정하고 시크릿 키로 application-dev.yml를 추가했습니다.

hofix: 설정 파일 분리

---

.github/workflows/deploy-to-dev.yml
.github/workflows/deploy-to-prod.yml

- 외부 private repository에 개발과 운영 환경의 application.yml을 추가했어요. 
- 외부 repository의 application.yml 파일을 가져와서 복사하도록 CD 스크립트를 수정했어요. 
- 필요한 시크릿 작성
- `github.config-repository`
- `github.token`

refactor: 개발 application.yml을 외부 repo에서 가져오도록 수정

---

.github/workflows/deploy-to-dev.yml
src/main/java/kr/allcll/seatfinder/AuthInterceptor.java
src/main/java/kr/allcll/seatfinder/CookieProperties.java
src/main/resources/application-local.yml
src/test/java/kr/allcll/seatfinder/star/StarServiceTest.java
src/test/java/kr/allcll/seatfinder/subject/SubjectServiceTest.java
src/test/resources/application.yml

쿠키에 아무런 설정이 되어 있지 않아서, 추가해요. 추가한 설정은 다음과 같아요. 
- httpOnly
- secure
- domain
- path
- sameSite
- maxAge
httponly, secure,samesite는 기본으로 설정했고, path는 최상단 경로인 `/`, 만료 시간은 영구에 가깝게 6년을 설정했어요. 6년이면 신입생이 졸업하고 남지 않을까요? ㅎㅎ

feat: 쿠키 설정 추가

---

.github/workflows/pull_request.yml
src/main/java/kr/allcll/seatfinder/basket/dto/BasketsEachSubject.java

- 스크립트에서 가능한 부분은 거의 **한글로 변경**했어요. 
- 서버 코드 (src/)에 변경이 없으면 테스트가 실행되지 않게 했어요. 
가독성이나 나중에 새로운 멤버가 온보딩하는 상황을 고려하여, 한글로 작성했어요. 그럼 이해하기 더 편하겠죠? 아래와 같이 변경되었슴니다~
서버 코드는 `src/` 경로에 있는데요. git diff 명령어를 사용해서 src/ 디렉토리에 변경이 없으면, 빌드와 테스트를 건너뛰도록 했어요. 
이를 위해 아래와 같이 job을 분리했는데요.
- check-app-changes: 서버 코드의 변경 여부를 확인하는 job
- build-and-test: 빌드와 테스트하는 job
check-app-changes에서는 변경 여부를 확인하고 `outputs.changed` 변수에 결과를 저장해요. 
build-and-test가 실행되기 전에 if 구문으로 위 변수를 확인하고 job의 실행 여부를 결정해요.

refactor: 서버 코드 수정 없으면 테스트하지 않도록 ci 스크립트 수정

---

.github/workflows/pull_request.yml
src/main/java/kr/allcll/backend/domain/basket/Basket.java

이전 #79 을 개선하는 내용이에요! 
해당 pr에서는 server 코드에 수정이 없으면 ci가 실행되지 않도록 했어요. 
이때 git diff를 사용했는데, 알고보니 github 워크플로에서 제공하는 기능이 있더군요. 
트리거에 server 폴더 경로를 추가하여 불필요한 job을 삭제했어요 😀

refactor: 불필요한 job 삭제

---

src/main/java/kr/allcll/backend/domain/seat/SeatApi.java
src/main/java/kr/allcll/backend/domain/seat/SeatRepository.java
src/main/java/kr/allcll/backend/domain/seat/SeatService.java
src/main/java/kr/allcll/backend/domain/seat/dto/PreSeatResponse.java
src/main/java/kr/allcll/backend/domain/seat/dto/PreSeatsResponse.java

미리 여석을 제공하는 api를 추가합니다. 이전에 지워졌던 [commit](https://github.com/allcll/allcll-backend/commit/f059b3d9c5de8ebea1e2792efab1b806696e35b8)을 되돌립니다.

hotfix: 미리 여석을 제공하는 api 추가

---

src/main/java/kr/allcll/backend/domain/seat/SeatService.java

날짜 설정이 잘못되어있었습니다. 이를 28일로 바꾸어주었어요

hotfix: preseat 날짜 수정

---

src/main/java/kr/allcll/backend/domain/seat/SeatService.java

hotfix: preseat 날짜 수정 (#90)

---

src/main/java/kr/allcll/backend/domain/seat/SeatStorage.java

교양과목을 여석이 0개 초과인 과목 중 낮은 순으로 20개를 가져옵니다.
사용자 맞춤형 정보가 될 것 같아서 이렇게 변경하기로 했어요

feat: nonMajor 정렬 로직 변경

---

build.gradle
src/main/java/kr/allcll/backend/support/sse/SseEmitterStorage.java
src/main/java/kr/allcll/backend/support/sse/SseMetrics.java

기존에 promethous로 메트릭 수집하는 방식에서 datadog로 메트릭 수집하도록 수정합니다.

chore: datadog 통합

---

src/main/java/kr/allcll/backend/client/ExternalService.java

메서드 작업단위가 너무 커서 쪼갰습니다.
완전 간단한 범위에요.
그래도 일단 피알 올립니다.
그리고 메서드명도 수정했는데...이거 좀 의견받고싶어요. 더 수정해야할거같은;;

refactor: 우선순위 적용 메서드 책임 분리

---

src/main/java/kr/allcll/backend/domain/subject/dto/SubjectResponse.java

https://www.notion.so/1c3acf7c31628188acbfd7d1e6267396?source=copy_link
요기에 있는 명세로 업데이트 했습니다!
하지만 totalCount는 아직 제공안되는 값이라서 뺐습니다! (합의 된 내용입니다.)

refactor: subject 요청 시 응답 필드 추가

---

.github/workflows/pull_request.yml

올클 CI에서는 병합생략, 최신화만 하는 것으로 수정했습니다.
병합하니까 터지더라구요

refactor: 올클CI 워크플로우 수정

---

.github/workflows/deploy-to-dev.yml
.github/workflows/deploy-to-prod.yml

workflow 수정했습니다.
운영 워크플로우에도 서브모듈을 끌고갈 수 있도록 적용해놓았고,
둘 다 브랜치를 checkout하도록 수정했습니다. 충돌을 예방하기 위함입니다.
또한 actions 로그에서 서브모듈의 어떤 해시를 끌고왔는지도 확인할 수 있도록 이를 추가했습니다.

refactor: workflow 수정

---

src/main/java/kr/allcll/backend/domain/timetable/TimeTableApi.java
src/main/java/kr/allcll/backend/domain/timetable/TimeTableService.java

TimeTable 생성해주는 api에서
- 기존에는 상태코드만 반환
- timeTableId, timeTableName, semester 반환

refactor: TimeTable 생성시 응답값 추가

---

src/main/java/kr/allcll/backend/config/WebMvcConfig.java

refactor: cors 추가

---

.github/workflows/deploy-to-prod.yml

fix: yml 수정

---

.github/workflows/deploy-to-prod.yml

refactor: 운영 배포 브랜치 변경

---

src/main/java/kr/allcll/backend/domain/basket/BasketService.java
src/main/java/kr/allcll/backend/domain/basket/dto/BasketsEachSubject.java
src/main/java/kr/allcll/backend/domain/subject/SubjectRepository.java
src/main/java/kr/allcll/backend/domain/subject/SubjectService.java
src/main/java/kr/allcll/backend/domain/subject/SubjectSpecifications.java
src/test/java/kr/allcll/backend/domain/basket/BasketApiTest.java
src/test/java/kr/allcll/backend/domain/basket/BasketServiceTest.java

* refactor: Basket 응답 포맷 수정
* test: Basket 응답 포맷 수정에 따른 테스트 수정
* refactor: Basket 관련 soft delete, 학기 조건 걸려있지 않은 것들 조건 추가

refactor: 관담 응답 포맷 수정 (#161)

---

src/main/java/kr/allcll/backend/admin/AdminApi.java
src/main/java/kr/allcll/backend/admin/AdminSessionApi.java
src/main/java/kr/allcll/backend/session/SessionService.java
src/main/java/kr/allcll/backend/session/dto/SessionStatusResponse.java

1. 프론트와 회의 진행한 결과에 따라, 현재 세션 갱신이 되고 있는지 여부를 확인하는 API를 추가적으로 구현했습니다.
2. admin 패키지 내, 기존 adminApi에서 adminSessionApi로 따로 분리해 역할 분리를 해줬습니다.
- Api 명세를 대략 추려본 결과, 어드민 api가 무수히 많습니다. 또한 도메인도 다양하게 존재하는데요. 관리 측면에서 생각해봤을 때, 그 많은 api를 스크롤 내리며 찾는 것보다는 도메인 별로 분리해서 관리하는 게 훨씬 효율적일 것 같다고 판단했습니다. 이는 계속 진행될 어드민 api 구현에서의 컨벤션으로 적용하기로 했습니다.
3. 포스트맨으로 정상 작동 확인했습니다. 캡쳐본도 첨부하고 싶지만, 보안상의 이유로 검증 흐름 설명드리겠습니다!
> 1. 인증 정보 세팅 api 호출합니다. 
- 200 OK가 뜨고, 위와 같이 현재 등록한 인증 정보가 로그로 나타납니다.
> 2. 인증 정보 조회 api를 호출합니다.
- 세팅했던 4가지 인증 정보가 정상적으로 반환됩니다.
>  3. 세션 갱신을 시작하는 api를 호출합니다.
- 200 OK가 뜨고, 해당 로그는 세션이 정상적으로 갱신되고 있을 경우 10초에 한 번 나타납니다.
> 4. (new) 현재 세션을 갱신 중인지 여부를 확인하는 api를 호출합니다.
- true가 반환됩니다.
>  5. 세션 갱신을 취소하는 api를 호출합니다.
- 더 이상 로그가 찍히지 않습니다.
> 6. 세션 갱신이 취소되었는지 여부를 확인하기 위해 다시 세션 갱신 여부 확인 api를 호출합니다.
- 정상적으로 false가 반환됩니다. 
> …

feat: 세션 갱신 여부 확인 API 추가 구현

---

src/main/java/kr/allcll/backend/client/ExternalClient.java
src/main/java/kr/allcll/backend/domain/basket/BasketService.java
src/main/java/kr/allcll/backend/domain/basket/star/StarService.java
src/main/java/kr/allcll/backend/domain/seat/pin/PinService.java
src/main/java/kr/allcll/backend/domain/timetable/schedule/ScheduleService.java
src/main/java/kr/allcll/backend/support/exception/AllcllErrorCode.java
src/test/java/kr/allcll/backend/domain/timetable/schedule/ScheduleServiceTest.java

과목 ID로 DB를 조회했을 때 존재하지 않는 경우, 로그에 subjectId 추가했습니다. 
에러 추적이 너무 어려워서요.

feat: 과목 ID로 DB를 조회했을 때 존재하지 않는 경우, 로그에 subjectId 추가

---

src/main/java/kr/allcll/backend/config/WebMvcConfig.java

refactor: cors admin 주소 추가

---

.github/workflows/deploy-to-prod.yml
src/main/java/kr/allcll/backend/config/WebMvcConfig.java

v0.1.2 릴리즈

---

src/main/java/kr/allcll/backend/client/ExternalClient.java

크롤러에 올린 pr에 따라 백엔드도 코드 수정했습니당
엄청 자그마한 변화라 그냥 함께 pr 올려요!! 크롤러가 머지되고 `git submodule update --remote`치면 아마 빨간줄 없어질거에용

refactor: 여석 갱신 시간 크롤러 단으로 이동

---

src/main/java/kr/allcll/backend/client/ExternalClient.java

hotfix: 쿼리 타임 백엔드로 롤백

---

src/main/java/kr/allcll/backend/client/ExternalClient.java
src/main/java/kr/allcll/backend/domain/subject/subjectReport/ReportTableBuilder.java

릴리즈 v0.1.4

---

src/main/java/kr/allcll/backend/support/semester/Semester.java
src/test/java/kr/allcll/backend/support/semester/SemesterTest.java

subject 응답이 안되는 경우가 있어 semester 정보를 수정했습니다

fix: 학기 정보 수정
