allcll/allcll-backend

build.gradle
src/main/java/kr/allcll/seatfinder/excel/ExcelSubject.java
src/main/java/kr/allcll/seatfinder/excel/SubjectSheetHeader.java
src/main/java/kr/allcll/seatfinder/excel/SubjectSheetHeaderMapper.java
src/main/java/kr/allcll/seatfinder/excel/SubjectSheetParser.java
src/main/java/kr/allcll/seatfinder/excel/SubjectsParsingResponse.java
src/main/java/kr/allcll/seatfinder/subject/Subject.java
src/main/java/kr/allcll/seatfinder/subject/SubjectApi.java
src/main/java/kr/allcll/seatfinder/subject/SubjectApp.java
src/main/java/kr/allcll/seatfinder/subject/SubjectRepository.java
src/main/java/kr/allcll/seatfinder/subject/SubjectRequest.java
src/main/java/kr/allcll/seatfinder/subject/SubjectService.java
src/main/java/kr/allcll/seatfinder/subject/SubjectsRequest.java
src/main/resources/application.properties
src/main/resources/application.yml
src/test/java/kr/allcll/seatfinder/excel/SubjectSheetHeaderMapperTest.java
src/test/java/kr/allcll/seatfinder/excel/SubjectSheetParserTest.java
src/test/java/kr/allcll/seatfinder/subject/SubjectApiTest.java
src/test/java/kr/allcll/seatfinder/support/fixture/SubjectExcelFileFixture.java

과목 엑셀파일을 업로드하는 기능을 구현했어요! 매학기마다 개설과목을 엑셀 파일로 공개하는데, 엑셀 파일을 업로드하면 자동으로 데이터베이스에 등록되도록 했습니다. 매우 편리한 기능입니다. 베이스 코드 없이 구현했기에 PR 내용이 다소 많은 점, 양해 부탁드려요. 
- 엑셀을 다루는 데에 Apache POI 라이브러리를 사용했어요. 자바 진영에서 가장 많이 사용하는 라이브러리라고 해요. 
- 엑셀을 직접 다루는 작업은 `excel` 패키지에 과목을 다루는 작업은 `subject` 패키지로 나누었어요. 의존성 방향은 (`subject` -> `excel`)으로 정했고, 의존성 분리를 위해 DTO를 여럿 만들었어요. 
엑셀 파일은 다음과 같이 구성되어 있어요. 24-2학기 엑셀 파일은 [여기](https://board.sejong.ac.kr/boardview.do?pkid=164996&currentPage=4&searchField=D.TITLE&siteGubun=19&menuGubun=1&bbsConfigFK=335&searchLowItem=ALL&searchValue=2%ED%95%99%EA%B8%B0)에서 다운받을 수 있어요. 
엑셀 파일의 상단, 컬럼명을 `SubjectHeader`라는 이름으로 코드에 작성해 두었어요. 참고 부탁해요! 엑셀 시트를 파싱하는 방식은 다음과 같아요. 
1. 헤더 컬럼을 파싱한다. 
2. 헤더를 구성한다. 
3. 데이터 컬럼들을 파싱한다. 
4. 파싱한 데이터로 `Subject` 객체를 만든다. 
여기서 까다로운 부분이 파싱한 데이터를 올바르게 `Subject` 객체로 변환하는 …

feat: 과목 엑셀파일 업로드 기능 구현 

---

src/main/java/kr/allcll/seatfinder/subject/SubjectApi.java
src/main/java/kr/allcll/seatfinder/subject/SubjectService.java

이전 PR에서 변경 내용 중 추가하지 못한 내용이 있었어요. 
dto들을 dto 패키지로 분리할 때, dto에 의존하던 클래스의 import 문을 커밋에 넣지 못했어요. 
재발 방지를 위해 ci를 두어야겠어요.

fix: 빠뜨린 import문 추가

---

.github/workflows/pull_request.yml

ci 스크립트를 작성했어요. 이전에 pr 요청에서 테스트 실행이 없어서 잘못된 커밋을 머지하는 일이 있었어요. 재방 방지를 위해 ci를 도입했어요. 
**ci 스크립트 작업 내용**
- main 브랜치에 pr 요청시 스크립트가 트리거돼요. 
- 현재 작업은 `빌드` -> `테스트` -> `테스트 결과를 코멘트에 작성` 으로 구성되어 있어요.

chore: pr 요청 시 테스트 실행하는 스크립트 작성

---

build.gradle
src/main/java/kr/allcll/seatfinder/sse/SseApi.java
src/main/java/kr/allcll/seatfinder/sse/SseEmitterStorage.java
src/main/java/kr/allcll/seatfinder/sse/SseService.java
src/test/java/kr/allcll/seatfinder/sse/SseApiTest.java
src/test/java/kr/allcll/seatfinder/sse/SseIntegrationTest.java

- SSE 연결하는 기능을 구현하고 API를 만들었어요. 
SSE에 대한 이해가 있어야 코드를 이해하기 쉬울 것 같아요. 제가 참고한 글은 [Tecoble](https://tecoble.techcourse.co.kr/post/2022-10-11-server-sent-events/)이에요! PR을 이해하기 위해 SSE에 대해 반드시 알아야 할 부분은 다음과 같아요. 
- SSE 연결을 맺고 타임아웃 전까지 아무런 메시지를 보내지 않으면 503 에러를 받는다. 
- SSE 연결이 많아지면 SSE 메시지를 보내기 위한 스레드가 늘어난다. 이것이 병목 또는 장애를 유발할 수 있다. 
SSE 테스트가 좀 어렵더라고요. 레퍼런스도 찾지 못했어요. 만약 찾게 된다면 알려주시면 감사합니다 🙇 
SSE 테스트는 슬라이스로 진행하기에 다소 의미가 없다고 생각했어요. SSE 연결에 대해 통합 테스트(E2E 테스트이려나..)를 작성했고, 앞으로도 그럴 생각이에요! 테스트를 작성하면서 RestAssured를 사용했어요! 이것이 완전히 사용자의 요청과 유사한 테스트를 작성할 수 있다고 생각했기 때문이에요. RestAssured로 테스트를 작성했지만 SSE를 테스트하는 건 쉽지 않았어요. SSE로 메시지를 받아도 바로 연결이 끊기는 것은 아니었고,  RestAssured는 연결이 끊길 때까지 대기해요. 그래서 테스트 실행 시간이 굉장히 길어졌어요. SseEmitter를 생성할 때 연결 시간을 설정할 수 있는데, 이렇게 설정한 시간만큼 테스트가 대기하더군요. 그래서 SseService 메서드를 모킹해서 연결 시간이 짧은 …

feat: SSE 연결 구현

---

src/main/java/kr/allcll/seatfinder/exception/AllcllErrorCode.java
src/main/java/kr/allcll/seatfinder/exception/AllcllException.java
src/main/java/kr/allcll/seatfinder/exception/ErrorResponse.java
src/main/java/kr/allcll/seatfinder/exception/ExceptionMessage.java
src/main/java/kr/allcll/seatfinder/exception/GlobalExceptionHandler.java
src/main/java/kr/allcll/seatfinder/pin/PinService.java
src/test/java/kr/allcll/seatfinder/pin/PinServiceTest.java

- 공통 예외 코드를 작성하였습니다.
- 어플리케이션 코드는 최대한 깔끔하게 하고싶어서, `AllcllException`클래스에 ~~정팩메를~~ constructor 넣었어요. enum만 받으면 알아서 code랑 message만들어주게....
- 제가 작업하였던 pin api에 적용하고, 테스트에서도 커스텀 예외를 사용하도록 하였습니다.
- 테스트에도 커스텀 예외를 가져다 쓰니까 좋아요. 저번 pr에서 걱정했던 포인트들이 많이 해결되는 것 같어용. 관리 포인트도 줄고 휴먼에러로 불필요한 리소스를 낭비하지 않을 수 있을 것 같아요. 무슨 느낌인지 아시져
- AllcllException 커스텀 예외 클래스에 
```java
public static AllcllException of(int number, ExceptionMessage e) {
String exceptionMessage = String.format(e.getMessage(), number);
return new AllcllException(exceptionMessage, e.name());
}
```
요 부분이 있거든요? 이건 저희 핀 개수 제한이 있잖아요, 그 숫자 정보도 주려고 넣었는데요,,, 너무 저거 하나 때문에 만든 메서드인가 싶어서 다른 방법이 있을 지 고민하게 되어요! 재사용성이 너무 떨어질 것 같아서 좋은질 모르겠어요. `MAX_PIN_EXCEPTION("이미 %d개의 핀을 등록했습니다."),` 이 아이만을 위한 메서드이잖아요?..
이외에는 개선점이 어떤 것이 있을지 제시해주시면 감사하겠습니다🐥🐥

feat: 커스텀 예외 및 추가 GlobalExceptionHandler 적용

---

src/test/java/kr/allcll/seatfinder/subject/SubjectServiceTest.java

원래 전체 과목 조회를 처음에 선행해야 하니까 그 엔드포인트가 따로 있었잖아요?
근데 보니까 과목 검색 api에 아무 검색 정보도 안넣고 조회하면 전부 제공이 되게 되어있더라구요
그래서 그 기능 테스트만 추가했습니다.
그런데요, 저번에 주환님 리뷰를 받고 테스트 수정을 한 적이 있거든요? 그 때 받았던 피드백중에 테스트 메서드 딱 하나만 보고도 기능과 테스트하려는게 어떤 건지 알아야한다고 하셨었는데요,,
그런데 현재 Subject 관련 test들도 처음에 init되는 과목이 몇 개인지, 그런거를 파악하기가 너무 어려운 것 같아요.
주환님이 작성해 두신 테스트라 우선은 놔두었는데요, 혹시 다른 의도나 어쩔 수 없는 상황이 있었던 것 일까요?! 알려주세용

test: 전체 조회 기능 테스트 작성(검색 api를 활용할 수 있다.)

---

src/main/java/kr/allcll/seatfinder/pin/PinApi.java
src/main/java/kr/allcll/seatfinder/pin/PinService.java
src/main/java/kr/allcll/seatfinder/pin/dto/PinSubjectResponse.java
src/main/java/kr/allcll/seatfinder/pin/dto/SubjectIdResponse.java
src/main/java/kr/allcll/seatfinder/pin/dto/SubjectIdsResponse.java
src/test/java/kr/allcll/seatfinder/pin/PinApiTest.java
src/test/java/kr/allcll/seatfinder/pin/PinServiceTest.java

등록된 핀 조회하는 기능을 구현했습니다.
핀이 아무것도 없어두 예외처리는 하지 않았습니다. 예외가 아니라고 생각해서용. 추가적 로직도 구현하지는 않았어요. 그냥 빈 리스트를 반환해도 좋다고 생각해서용
그리고요 처음에 저희가 전체 과목에 대한 데이터를 전달해주고 시작하잖아요? 그래서 subjectId를 전해주는 것으로 명세를 수정했어요. 왜냐하면 그 과목에 대한 여석 정보도 항상 요청해야하잖아요. 그래서 id를 전해주는게 더 편리하겠다고 생각했습니다. 과목id로 바로 요청하면 되니까용.
쓰다보니 드는 생각이, 핀 등록한 여석 정보는 폴링 방식으로 해도 되겠다는 생각이 드네요?... 이건 합의 후 구현하기 나름일 것 같습니다.
제가 빼놓은 정책이 있는지 한 번 검토 같이 해 주시면 감사하겠습니다

feat: 핀 조회 기능 구현

---

.github/workflows/deploy-to-dev.yml

dev 환경에서 AWS RDS에 연결되지 않는 문제가 있었습니다. 문제가 발생하고 info 레벨의 로그를 확인했고 결과는 아래와 같습니다. 
profile은 dev로 의도한대로 설정됩니다. dev 환경의 profile은 MySQL을 사용하도록 설정되어 있습니다. 하지만 로그를 확인하면 h2가 연결되는 것을 볼 수 있어요. 이는 빌드된 jar 내부에 default 설정 파일이 실행되는 걸로 유추할 수 있어요. 
1. EC2의 /home/ubuntu/app 경로에 jar 파일을 배포합니다. 
2. EC2의 /home/ubuntu/app 경로에 application-dev.yml을 작성합니다. 
3. 동일한 EC2에 self-hosted runner를 설치하여 workflow를 실행합니다. 
4. workflow에서 springboot 애플리케이션을 실행하는 명령줄은 다음과 같습니다. 
- `sudo nohup java -Dspring.profiles.active=dev  -Duser.timezone=Asia/Seoul -Dlogging.file.path=/home/ubuntu/app/logs -jar /home/ubuntu/app/server.jar & `
1-4를 진행하면 다음과 같이 세팅됩니다. 
application-dev.yml을 스캔하지 못하는 걸로 결론을 냈습니다. [스프링 공식 문서](https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/boot-features-external-config.html#boot-features-exte …

hotfix: 설정 파일이 제대로 세팅되지 않는 문제 해결 

---

src/main/resources/logback-spring.xml

기본으로 설정되어 있는 local 프로파일에서 스프링 애플리케이션을 실행하면 로그를 확인할 수 없는 문제가 있었습니다. 
logback 설정 파일에 local에서 사용할 로거를 설정하지 않아서 발생한 문제입니다.

fix: 로컬에서 사용하는 로거 설정

---

src/main/java/kr/allcll/seatfinder/basket/BasketService.java
src/main/java/kr/allcll/seatfinder/basket/dto/SubjectBasketsResponse.java
src/main/java/kr/allcll/seatfinder/subject/Subject.java
src/test/java/kr/allcll/seatfinder/basket/BasketApiTest.java
src/test/java/kr/allcll/seatfinder/basket/BasketServiceTest.java
src/test/java/kr/allcll/seatfinder/support/fixture/SubjectFixture.java

관담 세부 조회에 에타 링크 추가하는 작업을 했어요. 
- 작업한 URL: /api/baskets/{subjectId}
- 변경된 응답: 
```json
{
"everytimeLectureId": 1234567,
"eachDepartmentRegisters": [
{
"studentBelong": "본교생",
"registerDepartment":"컴퓨터공학과",
"eachCount": 10
},
{
"studentBelong": "본교생",
"registerDepartment":"전자정보통신공학과",
"eachCount": 4
}
]
}
```
- Subject 테이블에 everytime_lecture_id 컬럼을 추가했어요. 
- 크롤링한 데이터를 prod 데이터베이스에 반영했어요. 
- Subject Entity에 everytimeLectureId 컬럼을 추가했어요. 
- Basket을 조회할 때 subject도 함께 조회하게 되는데, subject에서 에타 LectureId를 찾아서 Basket 응답에 넣어줬어요. 
- 클라이언트는 응답으로 온 LectureId 앞에 도메인을 붙여서 링크를 걸면 돼요. `https://everytime.kr/lecture/view/` + `1234567`
- 현재는 도메인과 엔티티 사이의 경계가 애매한데요, Subject 도메인에 에타 링크가 들어가는 게 굉장히 어색해요. 과목은 그 자체로 순수하게 보존되어야 하는데, 외부 서비스의 정책이 들어온 거니깐요. 기한이 급하기 때문에 일단은 Subject 도메인에 넣었는데, 추후 개선이 필요할 것 같아요.

feat: 관담 세부 조회에 에타 링크 추가

---

src/main/java/kr/allcll/seatfinder/exception/AllcllErrorCode.java
src/main/java/kr/allcll/seatfinder/pin/Pin.java
src/main/java/kr/allcll/seatfinder/pin/PinRepository.java
src/main/java/kr/allcll/seatfinder/pin/PinService.java
src/main/java/kr/allcll/seatfinder/star/Star.java
src/main/java/kr/allcll/seatfinder/star/StarApi.java
src/main/java/kr/allcll/seatfinder/star/StarRepository.java
src/main/java/kr/allcll/seatfinder/star/StarService.java
src/main/java/kr/allcll/seatfinder/star/dto/StarredSubjectIdResponse.java
src/main/java/kr/allcll/seatfinder/star/dto/StarredSubjectIdsResponse.java
src/test/java/kr/allcll/seatfinder/star/StarApiTest.java
src/test/java/kr/allcll/seatfinder/star/StarServiceTest.java
src/test/java/kr/allcll/seatfinder/subject/SubjectServiceTest.java

즐겨찾기 기능을 구현했습니다.
현재는 등록 기능만 구현해두었구요, 추후 계속 커밋 추가하겠습니다.
기존 핀 기능처럼 5개로 제한해두었어요. 핀 기능은 5개 제한인데 이거는 제한이 없는건 이상한 것 같아서요.
리뷰와 병렬적으로 가져가고자 우선 pr 올립니다.

feat: 즐겨찾기 기능을 구현한다.

---

.github/workflows/deploy-to-dev.yml
.github/workflows/deploy-to-prod.yml

운영 환경에 배포하는 스크립트 작성했어요. 
dev 환경을 구성했던 것처럼 prod 환경에 필요한 변수들, actions runner 등을 새로 설정했어요. 
release 브랜치에 push 될 때 배포되도록 트리거를 걸었어요. 
정상 동작 확인했고, 바로 머지해도 괜찮을 것 같아요.

chore: 운영 환경 배포 스크립트 작성

---

build.gradle

이전에 excel 관련 코드는 지웠는데 의존성은 그대로네요! 지웠습니다. 바로 머지해도 괜찮을 것 같아요.

chore: 사용하지 않는 excel 의존성 제거

---

build.gradle
src/main/resources/application-local.yml

모니터링 환경을 구축했어요. 어떤 툴을 사용할지 고민했고, 우선순위는 비용(돈)과 비용(시간)이에요. 
가장 빨리 할 수 있는 것은 많이 다뤄본 프로메테우스, 그라파나 조합이에요. 
돈이 덜 드는 것은 AWS CloudWatch를 사용하는 것이에요. 
저는 전자를 택했는데, 이유는 프로메테우스, 그라파나를 띄울 서버 용량이 남기 때문이에요. 
가장 빨리 작업할 수 있는 방법을 택했어요. 
해당 PR에는 actuator와 Prometheus 설정만을 담고 있어요. 바로 머지해도 될 것 같아요.

chore: 모니터링 환경 설정 추가

---

.github/workflows/deploy-to-dev.yml
src/main/java/kr/allcll/seatfinder/seat/SeatService.java
src/main/java/kr/allcll/seatfinder/sse/SseApi.java
src/main/java/kr/allcll/seatfinder/sse/SseEmitterStorage.java
src/main/java/kr/allcll/seatfinder/sse/SseService.java

fix: 핀으로 등록한 과목의 여석 정보가 SSE로 전달되는 속도가 일정은 문제 해결

---

src/main/java/kr/allcll/seatfinder/exception/AllcllErrorCode.java
src/main/java/kr/allcll/seatfinder/exception/AllcllException.java
src/main/java/kr/allcll/seatfinder/exception/GlobalExceptionHandler.java
src/main/java/kr/allcll/seatfinder/sse/SseErrorHandler.java

- 에러 코드를 리팩터링 했어요. 도메인 별로 구분 잘되게 모아두었어요. 
- ServletException을 발생하는 경우에 404 NOT FOUND가 발생하게 했어요. 
- ServletException를 상속하는 클래스를 보면, 존재하지 않는 API에 요청을 보내는 경우, 잘못된 Http Method로 요청하는 경우, 파라미터를 설정하지 않은 경우 등, 웹 요청에서 발생하는 에러들이 모여 있어요. 
- 이걸 한 번에 404 NOT FOUND도 묶어도 괜찮을까요? 
- 우리가 핸들링 할 수 있는 에러는 AllcllException으로 처리하고, 그 외에 어떤 에러가 나올지 모르는 부분은 RuntimeException을 발생하게 했어요. 그럼 Exception을 핸들링하는 코드에서 잡히게 되고 ERROR 레벨로 로깅이 돼요. 따라서 RuntimeException을 throw하는 코드에서는 별도의 로깅 로직을 넣지 않았어요.

refactor: 에러 핸들링 개선

---

.github/auto_assign.yml

이 스크립트를 추가하면 우측에 Assignees와 Reviewers를 자동으로 설정해 준다고 하네요! 
저도 안 써봐서 어떻게 동작할지 모르겠지만, 예상하는 동작은 아래와 같아요. 
- Assignees는 작성자로 자동 할당
- Reviewers는 작성자를 제외한 나머지 인원 자동 할당

chore: 리뷰어, 작업자 자동 구성 스크립트 추가

---

src/main/java/kr/allcll/backend/client/ExternalService.java
src/main/java/kr/allcll/backend/config/ExternalConfig.java
src/main/java/kr/allcll/backend/config/ExternalPreInvoker.java

요구사항 변경으로 교양 탑20을 크롤러에 전송하는 기능을 삭제합니다. 
**기존 요구사항**
백엔드 서버에서 교양 탑20을 선정하여 크롤러에게 요청을 보내는 형태였습니다. 
**새로운 요구사항**
전체 교양 과목의 여석 데이터를 받고, 백엔드 서버에서 교양 탑 20을 선정하는 방식으로 변경합니다. 
백엔드 서버와 크롤러 간에 여석 데이터는 SSE를 통해 전송됩니다. 
백엔드 서버에 어떤 데이터를 전달할 것인지 결정하는 주체는 크롤러 서버입니다. 
크롤러 코드를 수정하여 전체 교양의 여석 데이터를 전송하는 방식으로 수정해야 하므로, 이 pr에서는 코드를 제거하는 작업만 했습니다.

remove: 교양 탑20을 크롤러에 전송하는 기능 삭제

---

src/main/java/kr/allcll/backend/domain/util/SemesterCode.java
src/main/java/kr/allcll/backend/domain/util/UtilApi.java
src/main/java/kr/allcll/backend/domain/util/UtilService.java
src/main/java/kr/allcll/backend/domain/util/dto/SemesterResponse.java
src/main/java/kr/allcll/backend/support/exception/AllcllErrorCode.java
src/test/java/kr/allcll/backend/domain/util/SemesterCodeTest.java
src/test/java/kr/allcll/backend/domain/util/UtilApiTest.java
src/test/java/kr/allcll/backend/domain/util/UtilServiceTest.java

현재 학기의 서비스 기간을 조회하는 API를 구현했어요. 이 API는 현재 학기(2025년 1학기)에 올클의 서비스 기간을 조회하는 API에요. 
아래 응답을 기반으로 25년 1학기 서비스 기간이 `2월 1일부터 3월 31일까지`라는 사실을 클라이언트가 알 수 있어요. 
이 데이터로 해당 학기 서비스 종료 여부를 사용자에게 표시해 줄 수 있겠죠! 
응답은 다음과 같아요. 
**`Request: GET /api/semester`**
```json
{
"semester": "2025-1",
"period": {
"start": "2025-02-01",
"end": "2025-03-31"
}
}
```
api의 응답 데이터인 학기와 기간은 mysql에서 관리하는 데이터에요. 관리자가 매 학기마다 데이터를 저장해야 해요. 
자동화한 부분도 있는데요. 코드 레벨에서 1-6월은 1학기, 7-12월은 2학기로 설정해 두었어요! 
6월에 api를 호출하면 시간을 기반으로 25년1학기 데이터를 조회하고, 7월에는 25년 2학기 데이터를 조회해요. 
추후 변경이 필요한 지점이에요. 작성한 테스트는 현재 시간을 기반으로 두고 있는데요. 7월이 되면 실패하는 테스트가 돼요. 이것은 테스트용 클락을 빈으로 등록하면 해결할 수 있어요. 이 내용은 추후 다른 pr에서 적용하는 게 어떨까해서 구현하지 않았어요!

feat: 현재 학기의 서비스 기간 조회 API 구현

---

src/main/java/kr/allcll/backend/admin/AdminApi.java
src/main/java/kr/allcll/backend/admin/AdminController.java
src/main/java/kr/allcll/backend/admin/AdminService.java
src/main/java/kr/allcll/backend/config/AdminConfigStorage.java
src/main/java/kr/allcll/backend/domain/seat/SeatService.java
src/main/java/kr/allcll/backend/support/exception/AllcllErrorCode.java
src/main/java/kr/allcll/backend/support/exception/AllcllSseException.java
src/main/java/kr/allcll/backend/support/schedule/ScheduleStorage.java
src/main/java/kr/allcll/backend/support/sse/SseService.java
src/test/java/kr/allcll/backend/admin/AdminServiceTest.java

멀티 모듈의 사용은 추후 도입하기로 결정 후, 현재 프로젝트에서 어드민 기능을 구현했습니다.
그리고, 아직 학기 정보 세팅에 관한 pr이 머지가 안되어서 해당 기능은 구현하지 않았습니다. 머지 이후 따로 pr을 파도 좋을 것 같아요.
저희가 SSE 연결을 통제하기 위해 `AdminConfigStorage`를 사용하는데요, 여기의 sseAccessible의 상태값이 `false` 일 경우 sse의 connect, propagate가 전부 예외를 발생합니다. 이 상태를 관리하는 api를 두개로 갈라서 만들었어용.
이때 이미 상태가 바꾸려는 상태와 동일하다면 예외를 던져줍니다.
핀 고정 과목은 클라이언트에서 요청이 오면 그 때 sse 응답을 시작하는데요, 이와 달리 교양과목은 별도의 클라이언트 요청 없이 응답을 계속 전송합니다. 이전엔 `@Scheduled` 어노테이션을 사용했었으나 sse 연결 관리의 불편함때문에 taskScheduler로 변경해주었어요. 따라서 어드민 페이지에서 요청을 직접 관리하는 방향으로 구현을 했습니다.
sse 연결을 불가능하도록 세팅했을 때, 기존에 이미 일정 주기로 돌아가던 스케줄러는 계속 돌아갑니다. 따라서 Runnable에서 예외를 catch 후 스케줄을 취소하는 로직으로 수정했습니다. 이 로직이 정상 작동하는지 메서드 콜로 테스트하는게 아닌 **직접 테스트 코드 내부에서 Runnable을 작성**하여 테스트를 해보았습니다. 테스트의 검증 방법에 대해 부연 설명을 하자면 다음과 같아요.
Runnable의 task에서 AtomicInteger가 증가하고, 예외를 catch 했을 때 …

feat: 어드민 기능 구현

---

src/main/java/kr/allcll/backend/domain/basket/BasketRepository.java
src/main/java/kr/allcll/backend/domain/basket/star/StarRepository.java
src/main/java/kr/allcll/backend/domain/seat/SeatRepository.java
src/main/java/kr/allcll/backend/domain/seat/pin/PinRepository.java
src/main/java/kr/allcll/backend/domain/seat/pin/PinService.java
src/main/java/kr/allcll/backend/domain/subject/SubjectRepository.java
src/main/java/kr/allcll/backend/support/entity/BaseEntity.java

Subject의 변경이 많은 것으로 파악되어 soft delete를 적용, 해당 설정을 포함하여 쿼리가 적용되었어야 했어요
쿼리들 작성한 pr 입니다.
그리고 과목을 고정해뒀던 pin과 star의 삭제와 같은경우엔 soft delete된(삭제된) 과목이더라도 제거가 되어야하므로 soft delete 설정과 상관없이 쿼리날리도록 해보았습니다.

feat: Subject 엔티티에 soft delete 적용

---

src/main/java/kr/allcll/backend/domain/seat/SeatStorage.java
src/test/java/kr/allcll/backend/domain/seat/SeatStorageTest.java
src/test/java/kr/allcll/backend/fixture/SubjectFixture.java

SeatStorage 클래스 가독성을 개선합니다. 기존에 없던 테스트도 추가합니다. 
SeatStorage는 여석을 관리하는 저장소입니다. 내부에 Map<Long, SeatDto> 자료구조를 관리하고 있습니다. 
key로 과목 ID을 사용하고 있는데, Long이라는 자료구조는 과목 ID라는 점을 명시적으로 표현하지 않습니다. 
과목 ID라는 value object를 만들까 고민하던 찰나, key를 Subject.class로 두어도 된다는 사실을 알았습니다. 이 변경으로 인해 외부에 어떠한 전파도 없습니다. 
Subject.class를 key로 쓴다면 주의할 점은 equals와 hashcode인데요. Subject.class는 id값으로 동등성을 비교하기 때문에 문제 없습니다. 
getSeats 메서드는 특정 과목의 여석 정보를 조회하는 기능입니다. 만약 SeatStorage가 관리하지 않는 과목의 여석 정보를 요청한다면 어떻게 되어야 할까요? 
예외를 발생할 수 있을 것 같습니다. 하지만 이는 적절하지 않다고 판단했는데요. 10개의 과목 여석을 요청했는데, 1개 과목의 여석 정보가 없는 상황에서 예외를 터뜨리는 게 좋을까요? 우리가 의도한 상황이 아님은 분명하지만 예외를 터뜨린다면, 9개 과목의 여석 정보는 전달하지 못합니다. 예외를 터뜨리진 않은 채로, warn 레벨 로깅 정도만 남기게 했습니다. 모니터링 중에 이 로그가 보인다면 조치가 필요할 것 같아요. 
제안입니다! 로깅 남길 때, 클래스 정보를 포함해서 남기면 어떨까요? 다음과 같이요! 그럼 로그가 어떤 코드 지점에서 발생했는지 파악하기 용이할 것 …

refactor: SeatStorage 클래스 가독성을 개선

---

src/main/java/kr/allcll/backend/domain/seat/Seat.java
src/main/java/kr/allcll/backend/domain/seat/dto/PreSeatResponse.java

Seat 테이블에 Subject 테이블의 컬럼이 많이 포함되어 있습니다. 아래 이미지는 Seat 테이블에 존재하는 Subject 테이블의 컬럼입니다. Seat 테이블에는 Subject.id가 이미 존재하는데 아래 컬럼이 존재하는 것이 이상했습니다. 
왜 이런 테이블이 만들어졌을까 고민해 보았고, 여석 API의 응답을 그대로 테이블로 만들었다는 사실을 알았습니다. 아래는 여석 API 응답의 일부입니다. 
```json
{
"SMT_CD": "21",
"REMAIN_TOT_RCNT": 123,
"TOT_LIMIT_RCNT_1": 0,
"OUT_LIMIT_RCNT": 0,
"CLASS": "001",
"TOT_LIMIT_RCNT_4": 0,
"TOT_LIMIT_RCNT_3": 0,
"TOT_LIMIT_RCNT_2": 0,
"RCNT": 1,
"YEAR": "2024",
"OUT_LIMIT_RCNT_2": 0,
"OUT_LIMIT_RCNT_1": 0,
"TOT_RCNT": 77,
"STUDENT_DIV_NM": "본교생",
"STUDENT_DEPT_CD_NM": "교육학과",
"CURI_NO": "011183",
"OUT_LIMIT_RCNT_4": 0,
"OUT_LIMIT_RCNT_3": 0,
"TOT_LIMIT_RCNT": 200,
"REMAIN_OTHER_RCNT": 123,
"TOT_OUT_RCNT": 76,
"REMAIN_OUT_RCNT": 0,
"DEPT_CD": "9005",
"STUDENT_DEPT_CD": "2114",
"ORGN_CLSF_CD": "20",
"STUDENT_DIV": "10"
} …
```

refactor: 여석 엔티티에 불필요한 필드 삭제

---

src/main/java/kr/allcll/backend/admin/AdminApi.java
src/main/java/kr/allcll/backend/admin/AdminService.java
src/main/java/kr/allcll/backend/config/ScheduleConfig.java
src/main/java/kr/allcll/backend/domain/seat/GeneralSeatSender.java
src/main/java/kr/allcll/backend/domain/seat/SeatService.java
src/main/java/kr/allcll/backend/domain/seat/SeatStorage.java
src/main/java/kr/allcll/backend/support/schedule/ScheduledTaskHandler.java
src/main/resources/application-local.yml
src/test/java/kr/allcll/backend/domain/seat/GeneralSeatSenderTest.java
src/test/java/kr/allcll/backend/domain/seat/SeatServiceTest.java
src/test/java/kr/allcll/backend/domain/seat/SeatStorageTest.java
src/test/java/kr/allcll/backend/support/schedule/ScheduledTaskHandlerTest.java
src/test/java/kr/allcll/backend/support/sse/SseServiceTest.java

스케줄링을 개선하는 작업을 진행했습니다. 스케줄링 개선은 4가지 목표를 갖고 진행했습니다. 
1. 스케줄링 작업마다 별도의 스레드 풀로 관리합니다. (ex. 교양 스케줄링 따로, 전공 스케줄링 따로)
2. 스케줄링 모니터링합니다. 
3. 스케줄링 작업을 제어할 수 있어야 합니다. 
4. 스케줄링이 다른 테스트에 영향을 주면 안됩니다. 
위 목적은 ScheduledTaskHandler.java 클래스를 만들어서 달성했습니다. 그리고 ScheduledTaskHandler.java를 사용해서 교양 스케줄링을 개선해 보았습니다. 
보다가 이해 안되는 부분이 있다면 편하게 물어봐 주세요~~ 😀 
ScheduledTaskHandler.java 필드와 생성자로 스레드 풀의 크기와 이름을 지정할 수 있습니다. 
```java
public class ScheduledTaskHandler {
private final ThreadPoolTaskScheduler scheduler;
...
public ScheduledTaskHandler(int poolSize, String namePrefix, MeterRegistry meterRegistry) {
scheduler = new ThreadPoolTaskScheduler();
scheduler.setPoolSize(poolSize);
scheduler.setThreadNamePrefix(namePrefix);
scheduler.initialize();
scheduler.setRemoveOnCancelPolicy(true);
...
}
```
위 코드에서 볼 수 있듯이 생성자에서 …

refactor: 스케줄링 4가지 개선(스레드풀 관리, 모니터링, 제어, 테스트에서 영향)

---

src/main/java/kr/allcll/backend/config/ClockConfig.java
src/main/java/kr/allcll/backend/domain/util/Semester.java
src/main/java/kr/allcll/backend/domain/util/SemesterCode.java
src/main/java/kr/allcll/backend/domain/util/UtilApi.java
src/main/java/kr/allcll/backend/domain/util/UtilService.java
src/main/java/kr/allcll/backend/domain/util/dto/SemesterResponse.java
src/test/java/kr/allcll/backend/domain/util/SemesterTest.java
src/test/java/kr/allcll/backend/domain/util/UtilApiTest.java
src/test/java/kr/allcll/backend/domain/util/UtilServiceTest.java

#109 이슈에 작성한 내용을 진행했습니다. 
- 테스트에서 시간 제어를 위해 Clock을 사용했습니다. 
- 애플리케이션 코드에는 현재 시간 Clock을 Bean으로 등록했고, 테스트 코드에서는 관련 테스트에서 모킹하는 방식을 택했습니다. 
- 테스트 코드에서 테스트용 고정 시간 Clock을 TestBean으로 등록해서 사용하는 방법도 있습니다. 이 방법을 선택하지 않은 이유는, 시간에 의존적인 테스트가 하나 밖에 없기 때문에 과하다는 생각을 했습니다.

feat: 서비스 기간 조회 api를 수정합니다

---

src/main/java/kr/allcll/backend/domain/seat/PinSeatSender.java
src/main/java/kr/allcll/backend/domain/seat/SeatService.java
src/test/java/kr/allcll/backend/domain/seat/SeatIntegrationTest.java
src/test/java/kr/allcll/backend/domain/seat/SeatServiceTest.java

핀 등록한 과목의 여석을 조회하는 로직을 PinSeatSender에서 SeatService로 옮겼습니다. 바로 아래 코드입니다. 아래 코드에서 주석으로 표시한 부분은 여석을 조회하는 로직으로, 이 책임을 SeatService로 이동하는 것이 적절하다 생각했습니다. 
```java
private Runnable getPinSeatTask(String token) {
return () -> {
if (sseService.isDisconnected(token)) {
scheduledTaskHandler.cancel(token);
return;
}
// 로직의 시작 부분
List<Pin> pins = pinRepository.findAllByToken(token);
List<Subject> subjects = pins.stream()
.map(Pin::getSubject)
.toList();
List<SeatDto> pinSeats = seatStorage.getSeats(subjects);
// 로직의 끝 부분
sseService.propagate(token, PIN_EVENT_NAME, PinSeatsResponse.from(pinSeats));
};
}
```
추가로 테스트 코드도 수정했어요. 
- **커밋 단위로 보면 이해하기 쉬울 거예요!** 
- 기존에 SeatService에는 비전공 여석을 SSE로 잘 전송하는지에 대한 테스트가 있었어요. 이것이 실제 SSE 커넥션을 맺고 데이터를 push 하는 전체 로직을 검증하더라고요. 통합 테스트의 느낌이 난다고 생각해서 `SeatIntegrationTest`로 …

refactor: PinSeatSender 코드 개선

---

src/main/java/kr/allcll/backend/domain/seat/GeneralSeatSender.java
src/test/java/kr/allcll/backend/domain/seat/GeneralSeatSenderTest.java

작업한 내용은 간단해서 커밋 별로 보지 않아도 괜찮을 것 같아요! 전체로 봐주세요. 
아래 2가지 작업을 했어요. 
- `hasActiveSchedule()` 메서드 분리
- 중복 스케줄링을 방지하는 로직에 대한 테스트 추가
교양 과목을 전송하는 로직에는 중복해서 스케줄링을 등록할 수 없는 조건이 존재해요. 아래 if문 조건이 그에 해당해요. 
지금은 이 조건이 무엇을 의미하는지 알지만, 시간이 흐르면 모를 수 있을 수 있고, 새로 온보딩하는 팀원은 이것이 왜 존재해야 하는 조건인지 모를 것 같더군요. 
그래서 의미있는 메서드명을 부여했어요! 
```java
public void send() {
if (scheduledTaskHandler.getTaskCount() > 0) {
return;
}
scheduledTaskHandler.scheduleAtFixedRate(getGeneralSeatTask(), SENDING_PERIOD);
}
```
말 그대로 중복 스케줄링을 방지하는 로직을 테스트했어요. 바로 위에 언급한 if문을 검증하는 것이에요! 이 테스트가 없더군요.

refactor: GeneralSeatSender클래스 가독성 개선

---

src/main/java/kr/allcll/backend/domain/seat/GeneralSeatSender.java
src/main/java/kr/allcll/backend/domain/seat/SeatService.java
src/main/java/kr/allcll/backend/domain/seat/SeatStorage.java
src/test/java/kr/allcll/backend/domain/seat/SeatIntegrationTest.java

저희가 이번 계절 수강 신청때에는 과목이 많이 없다보니 교양만 제공하는 것이 아닌 전체 과목을 제공하기로 했잖아요?  limit을 그래서 20개로 했었는데, 이번엔 창의학기제 제외 전체 과목 수인 39개로 늘렸습니다.
그리고 nonMajor인지 확인 후 필터링 하는 것도 제외했습니다.
새로운 api를 파기에는 프론트와도 맞추어야하는 것이고, 재사용하는 방향으로 논의가 되었다고 생각하고 있어서요. 우선은 그냥 주석 처리를 포함하여 기존 코드를 수정했습니다.
그리고 `/api/preSeat`을 수정했어요. 하드코딩되어있던데,,,, 전 날 크롤링 과목을 제공하면 되잖아요? 그래서 그 전날을 받아오게 했어요.
그런데 수강신청이 끝나고 며칠 지나면 마지막 정보를 전달해주기 힘들겠네요...크롤링을 더 안할테니까요. 근데 하드코딩하니까 너무 놓치기 쉬운 것 같아서 우선 그렇게 수정했습니다.
위의 변경에 따라, 교양만 전송하고, limit이 20개로 제한하는 기능의 테스트가 터져요.
그런데 우선은 재사용하기로 합의가 되었으니 주석처리를 하고 추후 주석 제거를 하는 방향이 맞다고 판단하여 주석 처리를 진행했습니다.
getAllPreSeat()에 대해 수정한 것 어떤지 의견 주면 감사하겠습니다. 수강신청이 끝나고 며칠 지나고 저 메서드를 호출하면 유효한 정보를 제공 못해주자나요. 마지막 날 정보도 못주고.....그게 걸리긴해요.

refactor: 하계 수강신청에 맞추어 로직 수정

---

src/main/java/kr/allcll/backend/support/entity/BaseEntity.java
src/main/java/kr/allcll/backend/support/entity/BaseEntityListener.java
src/main/java/kr/allcll/backend/support/semester/Semester.java
src/main/java/kr/allcll/backend/support/semester/SemesterResponse.java
src/main/java/kr/allcll/backend/support/semester/UtilApi.java
src/main/java/kr/allcll/backend/support/semester/UtilService.java
src/test/java/kr/allcll/backend/support/semester/SemesterTest.java
src/test/java/kr/allcll/backend/support/semester/UtilApiTest.java
src/test/java/kr/allcll/backend/support/semester/UtilServiceTest.java

베이스 엔티티가 하는 역할 중, semester_at을 세팅하는 것이 있습니다. 
이전 로직에서는 현재 semester를 알기 위해서 BaseEntityListener 내부에 별도 객체를 생성해서 사용했어요. 
당시에는 학기 정보를 알 방법이 없었기에 내부에 간단한 객체를 만들었어요. 
```java
public class BaseEntityListener {
@PrePersist
public void setSemester(BaseEntity entity) {
entity.createdAt = LocalDateTime.now();
entity.semesterAt = Semester.now();
}
private static class Semester {
private static final int MIDDLE_OF_YEAR_MONTH = 6;
public static String now() {
LocalDateTime now = LocalDateTime.now();
int year = now.getYear();
int month = now.getMonthValue();
return String.format("%d/%s", year, calculateSemester(month));
}
private static String calculateSemester(int month) {
return month <= MIDDLE_OF_YEAR_MONTH ? "1학기" : "2학기";
}
}
```
하지만 이후에 Semester라는 enum이 생성되었어요. 
```java
@Getter
public enum …
```

refactor: 베이스 엔티티 개선

---

src/main/java/kr/allcll/backend/admin/AdminService.java
src/main/java/kr/allcll/backend/domain/seat/PinSeatSender.java
src/main/java/kr/allcll/backend/support/sse/SseApi.java
src/main/java/kr/allcll/backend/support/sse/SseService.java
src/main/resources/application-local.yml
src/test/java/kr/allcll/backend/domain/seat/PinSeatSenderTest.java

핀과목 여석을 sse로 전송하던 스케줄링을 제어할 수 있게 수정했어요. 이제 어드민 API를 사용하면 `pin 과목 여석`과 `general 과목 여석` 둘다 제어할 수 있어요. 
pin 과목 여석을 제어할 수 있게 하면서 구조적인 변경이 있었어요. 
pin 과목 여석을 전송하는 sse 이벤트는 사용자가 sse 커넥션을 맺는 시점에 생성되어 1초마다 스케줄링 되었어요. 
```java
public class SseApi {
private final SseService sseService;
private final PinSeatSender pinSeatSender;
@GetMapping(value = "/api/connect", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
public ResponseEntity<SseEmitter> getServerSentEventConnection() {
String token = ThreadLocalHolder.SHARED_TOKEN.get();
SseEmitter emitter = sseService.connect(token);
pinSeatSender.send(token); // 이 부분
return ResponseEntity.ok()
.header("X-Accel-Buffering", "no")
.body(emitter);
```
스케줄링을 시작하고 끝내는 것의 제어권이 사용자에게 있었다고 할 수 있는데요. 사용자가 커넥션을 맺으면 스케줄링을 시작하니깐요. 
이 제어권을 우리 시스템이 갖고 오도록 수정했어요. general 여석 …

refactor: 핀과목 sse 스케줄링을 제어한다

---

src/main/java/kr/allcll/backend/domain/basket/star/Star.java
src/main/java/kr/allcll/backend/domain/seat/Seat.java

seats와 stars가 BaseEntity를 상속하지 않았습니다. 이 내용을 추가합니다.

fix: BaseEntity를 상속하도록 수정

---

.github/workflows/deploy-to-dev.yml

SSH 키를 적용하고, 서브모듈을 잘 가져올 수 있도록 workflow를 수정했습니다.
[이전 pr](https://github.com/allcll/allcll-backend/pull/135) 보다 이게 먼저 머지되어야해요! 이유는 pr이 머지되면 workflow가 돌아가기 때문입니다~!

refactor: 개발서버 배포 workflow 수정

---

.github/workflows/deploy-to-dev.yml
.github/workflows/pull_request.yml
.gitmodules

서브모듈 업데이트를 백엔드 배포 및 테스트와 동시에 하도록 워크플로우에 추가했습니다. 이러지 않으면 백엔드 코드는 변경 없고 서브모듈에 수정이 생기면 백엔드 코드도 항상 해시 갱신 하는 작업이 필요해요. 그래서 자동으로 가장 최신 해시 가져오도록 변경했습니다. (그래두 러너를 다시 돌려서 재배포 과정은 필요하겠지요)

refactor: 항상 서브모듈 최신 커밋 가져오도록 수정

---

src/main/java/kr/allcll/backend/domain/subject/SubjectService.java
src/main/java/kr/allcll/backend/domain/subject/SubjectSpecifications.java

subject 전체조회를 하면 지금까지 모든 과목을 조회한다는 이슈가 터졌습니다. 이번 학기 꺼만 조회해야하잖아요. 그래서 필터링에 걸어뒀습니다. condition 사용은 나중에 개선해도 될 것 같습니다.

hotfix: Subject 필터링 추가

---

src/main/java/kr/allcll/backend/domain/timetable/schedule/ScheduleService.java
src/test/java/kr/allcll/backend/domain/timetable/schedule/ScheduleServiceTest.java

1. 유효하지 않은 시간 요청값을 처리하는 로직을 구현했습니다.
2. 처리 로직에 대한 테스트를 작성하여 검증하였습니다.
3. 포스트맨으로 더블 체크 완료했습니다.
---
<현재 에러 상황>
CustomSchedule 등록 및 수정 시, 디폴트 값(=0시 or 00분)으로 설정 후 요청을 보내면 500 애러가 발생합니다.
이는 유효하지 않은 요청값이 넘어와서 LocalTime.parse 과정에서 에러가 발생하는 것으로 추측됩니다.
다음은 시간 요청값 예시입니다.
여러 상황을 가정하여 qa를 진행해본 토대로, 유효하지 않은 시간 요청값이 넘어오는 경우를 정리해보았습니다.
1. startTime 설정하지 않을 경우 
> - ui상의 디폴트 값은 0시 00분으로 표시됩니다.
> - 요청값으로는 "" 이 넘어옵니다.
2. 시 or 분을 설정 하지 않을 경우 
> - ui상의 디폴트 값은 0시 or 00분입니다.
> - 요청값으로는 "undefined:00" or "00:undefined"이 넘어옵니다.
3. 시간 설정값이 한 자리일 경우
> - 요청값으로 "7:00" "9:00" 포맷으로 넘어옵니다.
> - LocalTime이 파싱할 수 있는 포맷으로 변경하려면 한 자리수일 경우 두자리로 채워줘야 합니다.  ex) "07:00" "09:00"
>    그렇지 않으면 에러가 발생하는 것을 확인했습니다.
위의 예시들을 토대로 유효하지 않은 요청값들이 들어왔을 경우 정상 동작하도록 구현했습니다.
혹시라도 제가 언급드린 예시 말고, 에러가 날만한 다른 예시가 있다면 말씀해주세요!

fix: 유효하지 않은 시간 요청값 처리 로직 구현

---

src/main/java/kr/allcll/backend/client/ExternalClient.java
src/main/java/kr/allcll/backend/domain/seat/GeneralSeatSender.java
src/main/java/kr/allcll/backend/domain/seat/SeatStorage.java
src/main/java/kr/allcll/backend/domain/seat/dto/SeatDto.java
src/test/java/kr/allcll/backend/client/ExternalClientTest.java
src/test/java/kr/allcll/backend/domain/seat/SeatServiceTest.java
src/test/java/kr/allcll/backend/domain/seat/SeatStorageTest.java

여석을 변경지점만 주려다가 여러 사정 상 이번 서비스 기간에는 기존처럼 주게 되었습니다.
따라서 기존에 작성해두었던 변경 감지 로직을 삭제해야했습니다.
단순 롤백을 하기에는 서브모듈 작업도 이루어진 상태라, 롤백을 하진 않았고 다시 코드쳐서 구현했습니다.
크롤러에 `ChangeBuffer`말고 `AllSeatBuffer`를 도입하여 구현했습니다. 따라서 의존성이 AllSeatBuffer로 옮겨갔어용
정책 롤백에 따라 필요없어진 테스트가 있어서 주석처리한 것도 있습니다.
빠른 시일내에 다시 정책을 살릴 수도 있을 것 같아서...우선 남겨놨는데 지우고싶으면 추후 지워도 될듯...? 기간이 급하고 치명적인게 아니니...우선 냅다 주석처리했어요....
함께 페어마냥 했긴하지만 의아한지점이 있음 더 말씀해주세여

refactor: 여석 전송 로직 정책 롤백

---

src/main/java/kr/allcll/backend/domain/basket/BasketService.java
src/main/java/kr/allcll/backend/domain/basket/dto/BasketsEachSubject.java
src/main/java/kr/allcll/backend/domain/subject/SubjectRepository.java
src/main/java/kr/allcll/backend/domain/subject/SubjectService.java
src/main/java/kr/allcll/backend/domain/subject/SubjectSpecifications.java
src/test/java/kr/allcll/backend/domain/basket/BasketApiTest.java
src/test/java/kr/allcll/backend/domain/basket/BasketServiceTest.java

Subject 요청에 기존 Basket의 응답 값들을 포함하도록 변경하였습니다.
따라서 Basket의 응답 dto 구성을 변경하였습니다.
이에 따라 테스트들도 재구성했습니다.
또한 이걸 1학기 때 이후에 처음 쓰는 api라서(계절 땐 관담 없음) subject 조회에 soft delete나 학기 조건이 안걸려있는 것 같더라구요? 그래서 이거 걸어줬습니다.
필터링 조건 적절한지 크로스체크 해주세요!! 무슨 말이냐면 학과 같은 경우에는 semester at은 조건 걸면 안되잖아요? 그래서 soft delete랑 학기 조건 추가한 것들이 적절한지 한번 더 크로스체크해달라는 의미입니당

refactor: 관담 응답 포맷 수정

---

src/main/java/kr/allcll/backend/admin/AdminRequestValidator.java
src/main/java/kr/allcll/backend/admin/AdminSseApi.java
src/main/java/kr/allcll/backend/domain/seat/GeneralSeatSender.java
src/main/java/kr/allcll/backend/domain/seat/PinSeatSender.java
src/main/java/kr/allcll/backend/support/scheduler/SchedulerService.java
src/main/java/kr/allcll/backend/support/scheduler/dto/SeatSchedulerStatusResponse.java
src/main/java/kr/allcll/backend/support/sse/SseService.java
src/main/java/kr/allcll/backend/support/sse/dto/SseStatusResponse.java

기존에 존재하던 SSE 관련 API는 다음과 같습니다.
> 1. SSE 연결을 허용한다.
> 2. SSE로 여석 정보를 전달한다.
> 3. SSE 여석 정보 전달을 중단한다.
---
새로 구현한 API는 다음과 같습니다.
> 1. SSE 연결 상태를 확인한다. - true/false
> 2. SSE 여석 데이터 전송 여부를 확인한다. - true/false
새로 구현한 API가 나온 배경을 설명드리겠습니다.
최근 회의에서, 어드민 페이지를 만드는 목적에 대한 논의가 이루어졌습니다.
두 가지 방향성이 언급되었습니다.
> 1. Action에 대한 자동화
> 2. 모니터링 한 곳으로 모으는 역할
- 기존 운영 과정에서 포스트맨으로 수동 입력 + 프로세스대로 요청을 보내는 등의 불편함이 있었습니다. 
ex) header / 인증정보를 설정하는 부분이 번거로움.
2번 방향성으로 갈 경우, 포스트맨을 사용하는 것과 크게 다르지 않다는 의견이 나왔습니다.
따라서, 관리자가 편리하게 운영하고 대시보드를 통해 현재 운영 상황을 모니터링 하는 방향성으로 논의되었습니다.
자세한 내용은 회의록을 참고해주세요.
---
포스트맨으로 검증 완료했습니다.
해당 시나리오와 캡쳐본은 추후 추가하도록 하겠습니다.
1.**요청 간격 변수값 논의 필요**
어드민 API에서는 요청 IP를 기준으로 요청 간격과 토큰 유효성을 검사해 요청을 제한하거나 허용하도록 설계돼 있습니다. 기존에는 여석 전송과 여석 전송 중단 두 개의 API만 존재했고, 이 둘은 일반적으로 순차적으로 호출되기 때문에 요청 간 간격이 짧지 않았습니다. 그래서 요청이 너무 빠르게 …

feat: SSE 상태 판별 어드민 API 추가 구현

---

src/main/java/kr/allcll/backend/admin/AdminSeatApi.java

학과 크롤링 정보 관리 어드민 API를 구현했습니다.
크롤러의 여석 크롤링 api 중 admin 페이지에 사용되는 메서드들만 이동하였습니다.
- 일반 학기 여석 크롤링
- 계절 학기 여석 크롤링
- 여석 크롤링 종료
`여석 크롤링 상태에 대한 확인 로직`을 추가해야하는데 관련 내용이 `크롤러 레포 31번 PR`에 있어요. (링크를 첨부해도 되는지 모르겠어 따로 첨부는 하지 않았습니다)
방법 함께 의논해보고 따로 pr파서 구현하도록하겠습니다!

feat: 여석 관리 어드민 API 구현

---

src/main/java/kr/allcll/backend/session/SessionService.java

세션 갱신 실행 여부를 판별하는 로직을 수정했습니다.
기존에는 크롤러 - 스케줄러 핸들러의 내의 메서드를 사용하기 위해 taskId와 userId를 매핑하여 구현하였습니다.
taskId를 userId로 대체하여 Map 자료형을 쓰지 않고 좀 더 간편화 시키는 방향으로 수정했습니다.
기존, 크롤러 스케줄러를 관리하는 핸들러는 
1. Session 갱신 요청을 보내는 클래스와,
2. Seat 정보를 얻어오는 클래스
두 곳에서 쓰였습니다. 
하지만, 이는 config 클래스에서 각 스케줄러가 따로 관리되도록 설정되어 있으므로, 하나의 도메인에서 실행되는 스케줄러가 다른 도메인에서 실행되는 스케줄러에 영향을 주지 않습니다. 
따라서, taskId를 userId로 대체하여 쓰는 방식에서 문제가 생길 일은 없다고 판단했습니다.
---
포스트맨으로 정상 동작 확인했습니다.
나중에, 세션 갱신과 여석 정보 크롤링을 같이 실행할 때도 한 번 검증해보면 좋을 것 같아요.

refactor: 세션 갱신 실행 여부 판별 로직 수정

---

src/main/java/kr/allcll/backend/admin/AdminSseApi.java
src/main/java/kr/allcll/backend/support/sse/SseApi.java
src/test/java/kr/allcll/backend/support/sse/SseApiTest.java
src/test/java/kr/allcll/backend/support/sse/SseServiceTest.java

- SSE 연결 허용 및 차단 api 에 대한 컨텍스트 이해가 부족한 상태로 구현된 어드민 api 를 삭제하고, 클라이언트가 SSE 연결 시에 요청하는 api를 롤백했습니다.
추후 구현이 필요한 SSE 관련 API에 대해서 정리해보겠습니다.
1. SSE 연결을 허용하는 어드민 api
- 수강신청 기간 때에는 클라이언트가 SSE 연결을 맺을 수 있도록 허용한다.
2. SSE 연결을 차단하는 어드민 api
- 수강신청 기간이 아닐 때 SSE 연결이 자동으로 이루어지는 것을 방지한다.
3.  SSE 연결 상태를 확인하는 어드민 api
- 현재 SSE 연결을 허용하고 있는지 차단 중인지 확인한다.
해당 api 구현은 후순위로 두고, 시간적 여유가 생기면 그 때 진행하도록 합니다.

fix: 기존 SSE 연결 api 롤백

---

.github/workflows/deploy-to-dev.yml
build.gradle
src/main/java/kr/allcll/backend/admin/AdminSubjectApi.java
src/main/java/kr/allcll/backend/client/EmailProperties.java
src/main/java/kr/allcll/backend/config/EmailConfig.java
src/main/java/kr/allcll/backend/domain/subject/subjectReport/CrawlingMetaData.java
src/main/java/kr/allcll/backend/domain/subject/subjectReport/ReportTableBuilder.java
src/main/java/kr/allcll/backend/domain/subject/subjectReport/SubjectReportService.java
src/test/resources/application.yml

크롤러에서 작업했던 내용입니다.
기존에는 해당 작업이 크롤러 레포에서 진행되었습니다. 당시에는 admin API 작업 전이라, api, service 등 모든 비즈니스 로직이 크롤러 레포에 있었기 때문입니다.
하지만 admin API 작업 이후, API 클래스들을 모두 백엔드 레포로 이전했고, 크롤러 레포에는 최대한 크롤링 로직만 남기기로 하였습니다.
이에 따라 크롤러 pr #25에서 작성했던 로직 중 `과목 크롤링 시 과목 정보 변경 내역을 저장하는 기능`을 제외한 모든 로직을 백엔드 레포로 옮겼습니다.
아래는 크롤러 pr과 동일한 내용입니다
저희 서비스에서 과목 데이터는 가장 핵심적인 정보 중 하나이기 때문에, 과목 변경 사항을 보다 철저히 관리해야합니다. 시간표가 처음 공개된 이후 수강신청 기간까지 과목 정보는 지속적으로 변경되는데, 지금까지는 저희가 직접 크롤링을 수동으로 실행하고 SQL로 변경된 과목 개수를 확인하는 방식으로 관리하고 있었습니다.
이미 과목 정합성을 맞추는 로직은 크롤러의 SubjectSyncProcessor 클래스 내부에 구현되어 있으며, 과목 추가(In), 삭제(Out), 정보 수정(Update)를 정확하게 판별할 수 있습니다.
과목 크롤링을 실행하면 변경 내역이 자동으로 allcll 메일로 전송되도록 기능을 추가하였습니다. 메일 본문에는 다음과 같은 내용이 포함됩니다.
1. 과목 변경 집계 리포트
- 전체 과목 수
- 신규 추가 과목 수
- 폐강 과목 수
- 정보 변경 과목 수
2. 과목 정보 변경 세부 집계
- 추가된 과목 
- 삭제된 과목
- 수정된 과목 변경 내역
3. …

feat: 과목 동기화 리포트 이메일 발송 로직 이동

---

src/main/java/kr/allcll/backend/domain/subject/SubjectService.java

프론트의 요청으로 과목 조회 api에 폐강된 과목도 조회하도록 수정했습니다. 
프론트에서도 과목 폐강 여부를 알아야 합니다.

fix: 과목 조회 쿼리에 폐강된 과목도 조회하도록 수정

---

src/main/java/kr/allcll/backend/session/SessionService.java
src/main/java/kr/allcll/backend/session/dto/CredentialResponse.java

- 전반적으로 인증 정보에 대한 검증을 강화했습니다.
1. 인증 정보 세팅 후, 만료 시간이 지나도 인증 정보 조회 API 호출 시 정상적으로 조회되는 문제가 있었습니다.
이에 따라, 인증 정보가 유효한지 검사하는 메서드를 추가했습니다.
- 학교 서버에 요청을 보내, 정상 응답이 온다면 true
- 아니라면 예외가 발생하는데, 해당 예외를 catch하여 로깅 처리 및 false를 반환하도록 구현했습니다.
2. 인증 정보 세팅 시에도 문제가 있었습니다. 요청 필드값이 유효하지 않거나, 혹은 요청으로 들어온 인증 정보가 유효하지 않은 경우에도 정상적으로 저장되어 문제가 생겼습니다.
이에 따라, 요청 및 인증 정보 유효성 검사를 실행하는 메서드를 추가적으로 구현했습니다.
---
포스트맨으로 위 시나리오에 대비한 정상 작동 확인했습니다.

fix: 인증 정보 관련 어드민 API 검증 강화

---

src/main/java/kr/allcll/backend/domain/subject/subjectReport/ReportTableBuilder.java

1. 리포트에 softdeleted 여부를 확인하는 칼럼을 추가했습니다
isDeleted 여부를 확인하는 로직은 크롤러 36번 pr 참고해주세요!
(⚠️상태변경말고 isDeleted로 칼럼명 설정하였습니다!)
2. `-` -> `new`(=삭제되었다가 생김) 와 `-`(before와 after가 동일해 변경내역 없음) 가 헷갈려서 before과 after가 동일해 변경사항 없는 경우에는 점으로 표시됩니다! 
해당 로직 자체는 크롤러에 있습니다

refactor: seat report에 isDeleted 칼럼 추가

---

src/main/java/kr/allcll/backend/client/ExternalClient.java

사용자에게는 항상 크롤링한 시간을 보여야 합니다. 롤백되었던 로직(31640a07e7ae0f4177557f3f3ca5c329cc6b288c)을 다시 롤백합니다. 
관련해서 [크롤러 작업](https://github.com/allcll/allcll-crawler/pull/44)도 진행했습니다.

revert: "hotfix: 쿼리 타임 백엔드로 롤백"

---

src/main/java/kr/allcll/backend/admin/AdminPreSeatApi.java
src/main/java/kr/allcll/backend/admin/AdminSeatApi.java
src/main/java/kr/allcll/backend/domain/seat/SeatService.java
src/main/java/kr/allcll/backend/domain/seat/preseat/PreSeatApi.java
src/main/java/kr/allcll/backend/domain/seat/preseat/PreSeatService.java
src/main/java/kr/allcll/backend/domain/seat/preseat/dto/PreSeatsResponse.java

- seat 패키지 내 preseat 패키지를 만들어 두 로직을 분리하였습니다.
- 기존에 AdminSeatApi에 seat과 preseat로직이 함께 있었기에,  preseat관련 로직은 AdminPreSeatApi로 분리했습니다.
- SeatService내의 preseat관련 메서드 또한 분리하였습니다
postman으로 정상작동 확인하였습니다.

refactor: preseat로직 패키지 분리

---

src/main/java/kr/allcll/backend/admin/basket/AdminBasketApi.java
src/main/java/kr/allcll/backend/admin/basket/AdminBasketService.java

크롤러 의존도를 낮추기 위해 basket 관련 클래스들을 백엔드 코드로 이동합니다.
이동 대상이 되는 클래스들은 다음과 같습니다.
- `CrawlerBasketService`
- `CrawlerBasketApi`
기존 백엔드 코드의 domain > basket 패키지에도 BasketApi, BasketService가 있습니다. 이들은 관심과목 검색(GET - `/api/baskets?param=value`), 관심과목 정보 상세조회(GET - `/api/baskets/{subjectId}`)에 관한 로직입니다. 
해당 로직은 직접 관심과목 정보를 크롤링 하는 로직이므로 domain의 basket보다는 admin api로 이동하여 요청을 시도할 때 토큰 인증을 하고 하는것이 보안상 맞다고 판단되어 아래와 같이 작업하였습니다.
해당 로직은 직접 관심과목 정보를 크롤링하는 로직이므로, `domain > basket`보다는 admin API로 이동하여 요청 시 토큰 인증을 거치는 것이 보안상 더 적절하다고 판단했습니다.
이에 따라 아래와 같이 작업을 진행했습니다.
- admin > basket 패키지 생성
- `CrawlerBasektService` → `AdminBasketService` 이름 변경
- `CrawlerBasketApi` → `AdminBasketApi` 이름 변경
- Admin 토큰 검증 로직 추가
---
해당 로직을 Admin으로 관리하는 것에대해 적절한지, 더 나은 방법이 있는지 의견있으면 코멘트 부탁드립니다!

refactor: 크롤러 의존도 낮추기 위한 basket 클래스 백엔드 코드로 이동

---

src/main/java/kr/allcll/backend/admin/sse/AdminSseApi.java

admin 하위에 sse 패키지 생성 후 `AdminSseApi`를 이동하였습니다.
해당 Api는 총 세 가지입니다.
> 1. Sse 전송을 시작하는 API
> 2. Sse 전송을 중단하는 API
> 3. Sse 전송 여부를 확인하는 API
`AdminSseApi` 에서 사용하는 `SchedulerService`는 admin>sse 로 이동하지 않았습니다.
기존, support > schduler 패키지 하위에 두는 것이 역할 분리 측면에서 맞다고 판단하였습니다.
다른 패키지 분리 방안이 있다면 공유해주세요!

refactor: Sse 관련 어드민 API 패키지 경로 변경
